#########
# HOWARD #
#########
# Usage: docker-compose up

version: '3'

# SERVICES
##########

services:


    # HOWARD IMAGES
    ##############


    # HOWARD setup and test
    HOWARD-setup:
        image: ${DOCKER_HOWARD_SETUP_IMAGE}
        build:
            context: ${DOCKER_HOWARD_CONTEXT}
            dockerfile: Dockerfile
        container_name: ${DOCKER_HOWARD_SETUP_CONTAINER_NAME}
        entrypoint: /bin/bash
        command: ${DOCKER_HOWARD_SETUP_CONTAINER_COMMAND}
        volumes:
            # Docker sock
            - /var/run/docker.sock:/var/run/docker.sock
            # Databases
            - ${DOCKER_HOWARD_CLI_FOLDER_HOST_DATABASES}:${DOCKER_HOWARD_CLI_FOLDER_INNER_DATABASES}
        env_file:
            - ${DOCKER_COMPOSE_ENV}
        networks:
            - howard

    # HOWARD CLI
    HOWARD-CLI:
        image: ${DOCKER_HOWARD_CLI_IMAGE}
        container_name: ${DOCKER_HOWARD_CLI_CONTAINER_NAME}
        entrypoint: /bin/bash
        command: -c "echo '# Welcome to HOWARD Command Line Interface' && while true; do sleep ${DOCKER_HOWARD_CLI_SLEEP}; done"
        volumes:
            # Docker sock
            - /var/run/docker.sock:/var/run/docker.sock
            # Databases
            - ${DOCKER_HOWARD_CLI_FOLDER_HOST_DATABASES}:${DOCKER_HOWARD_CLI_FOLDER_INNER_DATABASES}:rw
            # Data
            - ${DOCKER_HOWARD_CLI_FOLDER_HOST_DATA}:${DOCKER_HOWARD_CLI_FOLDER_INNER_DATA}:rw
        restart: always
        env_file:
            - ${DOCKER_COMPOSE_ENV}
        networks:
            - howard


# NETWORK
###########

networks:
    howard:
        driver: "bridge"
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_HOWARD_SUBNET}